---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: ~/VagrantBoxes/ubuntu-12.04.box

suites:
- name: default
  run_list: [mics]
  attributes: {}
